"""initial schema

Revision ID: 0b45b20d1522
Revises: 
Create Date: 2026-09-02 12:58:56.170892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b45b20d1522'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bamboo_species',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name_local', sa.String(), nullable=False),
    sa.Column('name_scientific', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('density', sa.String(), nullable=False),
    sa.Column('culm_diam_range', sa.String(), nullable=False),
    sa.Column('wall_thickness_range', sa.String(), nullable=False),
    sa.Column('treatment_methods', sa.JSON(), nullable=False),
    sa.Column('structural_role', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bamboo_species', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bamboo_species_name_local'), ['name_local'], unique=False)

    op.create_table('joint_types',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('applicable_species', sa.JSON(), nullable=False),
    sa.Column('applicable_culm_sizes', sa.String(), nullable=False),
    sa.Column('load_notes', sa.Text(), nullable=False),
    sa.Column('failure_mode', sa.Text(), nullable=False),
    sa.Column('media_url', sa.String(), nullable=True),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('joint_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_joint_types_name'), ['name'], unique=False)

    op.create_table('templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('components', sa.JSON(), nullable=False),
    sa.Column('default_bom', sa.JSON(), nullable=False),
    sa.Column('known_span_range', sa.String(), nullable=False),
    sa.Column('hero_image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_templates_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_templates_name'), ['name'], unique=False)

    op.create_table('designs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('based_on_template_id', sa.String(), nullable=True),
    sa.Column('based_on_template_version', sa.String(), nullable=True),
    sa.Column('components', sa.JSON(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['based_on_template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('designs')
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_templates_name'))
        batch_op.drop_index(batch_op.f('ix_templates_category'))

    op.drop_table('templates')
    with op.batch_alter_table('joint_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_joint_types_name'))

    op.drop_table('joint_types')
    with op.batch_alter_table('bamboo_species', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bamboo_species_name_local'))

    op.drop_table('bamboo_species')
    # ### end Alembic commands ###
